[package]
name = "viewer3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34.0"
image = "0.24.8"
ndarray = "0.15.6"
nifti = "0.16.0"
winit = "0.29.10"
